### ISSUE TITLE
_min_this_week & _max_this_week

### ISSUE THREAD

**Issue by josephdyland** [SNoof85/lovelace-tempometer-gauge-card#1]
Love your Tempometer cards!

I am looking to create some entities for _min_this_week & _max_this_week on my BMP280 Pressure sensor.

I have entity sensor.bmp280_pressure,  How were you able to create the min and max based on previous week?

**Comment by SNoof85** [comment]
Hi, Thanks for your support :)

I'm using influxdb to store all my sensors datas coming from Home Assistant.
Then i created 2 sensors that are extracting back the min and max values for the current week with : 

```
platform: influxdb
host: 192.168.1.10
queries:
  - name: max pressure this week
    unit_of_measurement: mbar
    measurement: '"mbar"'
    group_function: max
    where: '"entity_id" = ''netatmo_salon_pressure'' AND time > {{(as_timestamp(now()) - (now().weekday() * 86400) - (now().hour * 3600) - (now().minute * 60) - (now().second)) | round(0)}}s'
    field: value
    database: hassio
  - name: min pressure this week
    unit_of_measurement: mbar
    measurement: '"mbar"'
    group_function: min
    where: '"entity_id" = ''netatmo_salon_pressure'' AND time > {{(as_timestamp(now()) - (now().weekday() * 86400) - (now().hour * 3600) - (now().minute * 60) - (now().second)) | round(0)}}s'
    field: value
    database: hassio
```
where my pressure sensor entity is `netatmo_salon_pressure`
