### ISSUE TITLE
I need to use the "style" tag for positionning

### ISSUE THREAD

**Issue by slurpey** [SNoof85/lovelace-tempometer-gauge-card#37]
Hi,
Not sure if this fits bug or else, but I can't figure out how to use my style tag for positioning.  The below doesn't work of course, but how can I code this?  Thanks
```
type: picture-elements
elements:
  - type: custom:tempometer-gauge-card
    entity: sensor.dsmr_reading_electricity_currently_delivered
    min: 0
    max: 2500
    decimals: 0
    severity:
      green: 400
      yellow: 700
      red: 1000
    title: Stroomverbruik
    style: 
      style: custom
      top: 32%
      left: 40%
image: 'https://demo.home-assistant.io/stub_config/floorplan.png'

```
